'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');

module.exports=async function productFlows({page,base,navigate,reveal,uploadProject,root,state}){
  const frames=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  async function screenshot(name){
    if(!process.env.WEB_TEST_SCREENSHOT_DIR)return;
    await page.evaluate(()=>window.scrollTo(0,0));await frames();
    await page.screenshot({path:path.join(process.env.WEB_TEST_SCREENSHOT_DIR,name),fullPage:true});
    if(name==='large-plan.png')await page.screenshot({path:path.join(process.env.WEB_TEST_SCREENSHOT_DIR,'large-plan-viewport.png')});
  }
  async function measure(action){const started=performance.now();await action();await frames();return Math.round(performance.now()-started);}
  await page.setViewportSize({width:1440,height:1000});
  await navigate('projects');
  // Dialog follows keyboard conventions and restores focus to its opener.
  await page.click('#newProject');
  await page.locator('#createProjectDialog').waitFor({state:'visible'});
  await page.keyboard.press('Escape');
  await page.locator('#createProjectDialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('#newProject').evaluate(el=>el===document.activeElement),true);
  await page.click('#newProject');
  await page.fill('#wizardName','Browser-Prüfung – Team A');
  await page.fill('#wizardStart','2026-02-02');
  await page.fill('#wizardEnd','2026-02-06');
  await page.fill('#wizardTimezone','Europe/Vienna');
  await page.click('#wizardNext');
  await page.fill('#wizardPeople','Testperson 001\nTestperson 002\nTestperson 003\nTestperson 004');
  await page.fill('#wizardPositions','Funktion A');
  await page.click('#wizardNext');
  await page.check('#wizardRulesConfirmed');
  await page.check('#wizardApprovalsConfirmed');
  await page.uncheck('#wizardContextConfirmed');
  await page.route('**/api/projects/new',route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'Bitte den gewählten Zeitraum prüfen.'})}),{times:1});
  await page.click('#wizardCreate');
  await page.waitForFunction(()=>document.querySelector('#wizardError').textContent.includes('Zeitraum prüfen'));
  assert.equal(await page.locator('#wizardName').inputValue(),'Browser-Prüfung – Team A');
  assert(await page.locator('#wizardRulesConfirmed').isChecked());
  assert(await page.locator('#createProjectDialog').isVisible());
  await screenshot('project-wizard.png');
  const createdResponse=page.waitForResponse(response=>response.url().endsWith('/api/projects/new')&&response.request().method()==='POST');
  await page.click('#wizardCreate');
  const created=await createdResponse;
  assert.equal(created.status(),200);
  const project=await created.json();
  const snapshot=project.snapshot??project;
  assert.equal(snapshot.employees.length,4);
  assert.equal(snapshot.period_start,'2026-02-02');
  await page.locator('#createProjectDialog').waitFor({state:'hidden'});
  await navigate('team');
  await page.waitForSelector('.matrix-cell');
  if(await page.locator('#transpose').getAttribute('aria-pressed')==='true')await page.click('#transpose');
  const approval=page.locator('.matrix-cell').first();
  await approval.click();
  assert.equal(await approval.getAttribute('aria-pressed'),'false');
  await page.click('#addPerson');
  assert.equal(await page.locator('#details').getByLabel('Name',{exact:true}).inputValue(),'');
  assert.equal(await page.locator('#details').getByLabel('Sollstunden im Planungszeitraum',{exact:true}).inputValue(),'');
  await page.locator('#details').getByLabel('Name',{exact:true}).fill('Testperson 005');
  await page.locator('#details').getByLabel('Name',{exact:true}).blur();
  await page.locator('#details').getByLabel('Sollstunden im Planungszeitraum',{exact:true}).fill('8');
  await page.locator('#details').getByLabel('Sollstunden im Planungszeitraum',{exact:true}).blur();
  const addedPersonSave=page.waitForResponse(response=>response.url().endsWith('/api/snapshots')&&response.request().method()==='PUT');
  await page.click('#save');
  const addedPerson=await(await addedPersonSave).json();
  assert.equal(addedPerson.employees.length,5);
  assert.equal(addedPerson.employees[4].target_minutes,480);
  await reveal('#people');
  await page.locator('#people tbody tr').nth(1).getByRole('button',{name:'Bearbeiten',exact:true}).click();
  await page.locator('#details').getByLabel('Name',{exact:true}).fill('Testperson 002 bearbeitet');
  await page.locator('#details').getByLabel('Name',{exact:true}).blur();
  await page.locator('#details').getByRole('button',{name:'Abwesenheit hinzufügen',exact:true}).click();
  await page.locator('#details').getByLabel('Abwesend ab',{exact:true}).fill('2026-02-02T00:00');
  await page.locator('#details').getByLabel('Abwesend bis',{exact:true}).fill('2026-02-03T00:00');
  const absenceResponse=page.waitForResponse(response=>response.url().endsWith('/api/intervals/resolve')&&response.request().method()==='POST');
  await page.locator('#details').getByRole('button',{name:'Abwesenheit übernehmen',exact:true}).click();
  assert.equal((await absenceResponse).status(),200);
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Abwesenheit übernommen'));
  const savedResponse=page.waitForResponse(response=>response.url().endsWith('/api/snapshots')&&response.request().method()==='PUT');
  await page.click('#save');
  const saved=await(await savedResponse).json();
  assert.equal(saved.employees.length,5);
  assert.equal(saved.employees[4].name,'Testperson 005');
  assert.equal(saved.employees[4].target_minutes,480);
  assert.equal(saved.context_complete,false);
  assert(saved.employees[0].approvals.every(grant=>grant.valid_until<saved.period_start||grant.valid_from>saved.period_end));
  assert.equal(saved.employees[1].name,'Testperson 002 bearbeitet');
  assert.equal(new Date(saved.employees[1].unavailable[0].start).toISOString(),'2026-02-01T23:00:00.000Z');
  // Reopening proves the editor wrote durable state, rather than only changing DOM.
  await page.reload();
  await reveal('#saved');
  await page.selectOption('#saved',saved.id);
  await page.click('#restore');
  await navigate('team');
  assert.equal(await page.locator('.matrix-cell').first().getAttribute('aria-pressed'),'false');
  await reveal('#people');
  assert.equal(await page.locator('#people tbody tr').count(),5);
  await page.locator('#people tbody tr').nth(4).getByRole('button',{name:'Bearbeiten',exact:true}).click();
  await page.click('#removePerson');
  await page.waitForFunction(()=>window.PlannerApp.getState().snapshot.employees.length===4);
  await navigate('rules');
  const contextConfirmation=page.locator('#contextConfirmation input[type="checkbox"]');
  assert.equal(await contextConfirmation.isChecked(),false);
  await contextConfirmation.check();
  await navigate('calculate');
  await page.fill('#limit','5');
  const jobResponse=page.waitForResponse(response=>response.url().endsWith('/api/jobs')&&response.request().method()==='POST');
  await page.click('#solve');
  const job=await(await jobResponse).json();
  await page.waitForFunction(()=>document.querySelector('#result').textContent.includes('Vollständig'),null,{timeout:30000});
  const completed=await(await fetch(base+'/api/jobs/'+job.id)).json();
  const jobInput=await(await fetch(base+'/api/jobs/'+job.id+'/snapshot')).json();
  assert.equal(jobInput.context_complete,true);
  assert.equal(jobInput.employees.length,4);
  assert.equal(jobInput.metadata.context_duty_free_confirmed,true);
  assert.equal(completed.state,'succeeded');
  assert(completed.result.validation.valid&&completed.result.validation.complete);
  await navigate('plan');
  const workbookDownload=page.waitForEvent('download');
  await page.click('[data-export="xlsx"]');
  const workbook=await workbookDownload;
  assert.match(workbook.suggestedFilename(),/\.xlsx$/);
  const workbookBytes=fs.readFileSync(await workbook.path());
  assert.equal(workbookBytes.subarray(0,2).toString(),'PK');
  assert(workbookBytes.length>2000);
  await screenshot('created-project.png');
  // Follow every summary page; searching can still reach a project beyond page one.
  const summaries=await(await fetch(base+'/api/snapshots?limit=1000')).json();
  const knownSummary=summaries.find(item=>item.id===saved.id);
  assert(knownSummary);
  const manyProjects=Array.from({length:1001},(_,index)=>({...knownSummary,id:`synthetic-project-${index}`,project_name:`Projekt ${String(index+1).padStart(4,'0')}`}));
  manyProjects[1000]={...knownSummary,project_name:'Abschlussprojekt 1001'};
  let summaryRequests=0;
  await page.route('**/api/snapshots?*',route=>{
    if(route.request().method()!=='GET')return route.continue();
    const url=new URL(route.request().url());summaryRequests++;
    const offset=Number(url.searchParams.get('offset')??0),limit=Number(url.searchParams.get('limit')??200);
    return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(manyProjects.slice(offset,offset+limit))});
  });
  await page.reload();
  await page.waitForFunction(()=>document.querySelector('#projectCount').textContent.replace(/\D/g,'')==='1001');
  assert(summaryRequests>=2,'Project summaries continue beyond the first API page');
  assert(await page.locator('.project-card').count()<=24,'Project cards are paginated');
  await page.fill('#projectSearch','Abschlussprojekt 1001');
  await page.waitForFunction(()=>document.querySelectorAll('.project-card').length===1);
  await page.locator(`.project-card[data-project-id="${saved.id}"]`).click();
  await page.locator('[data-panel="team"]').waitFor({state:'visible'});
  await page.waitForFunction(id=>window.PlannerApp.getState().snapshot?.id===id,saved.id);
  await page.unroute('**/api/snapshots?*');
  await page.reload();
  // Render-scale fixture is deliberately separate from solver benchmarks.
  let large,fixture='synthetic-render';
  if(process.env.WEB_TEST_PERFORMANCE_INPUT&&process.env.WEB_TEST_PERFORMANCE_RESULT){
    large=JSON.parse(fs.readFileSync(process.env.WEB_TEST_PERFORMANCE_INPUT,'utf8'));
    const result=JSON.parse(fs.readFileSync(process.env.WEB_TEST_PERFORMANCE_RESULT,'utf8'));
    assert(result.validation.valid&&result.validation.complete);
    large.assignments=result.assignments;fixture='validated-benchmark';
  }else{
    large=JSON.parse(execFileSync(process.env.WEB_TEST_PYTHON||'python3',['-c','from sp5generator.demo import make_demo; print(make_demo(120,31).model_dump_json())'],{cwd:root,encoding:'utf8',maxBuffer:8*1024*1024}));
    large.assignments=large.demands.flatMap((demand,index)=>Array.from({length:demand.minimum},(_,offset)=>({employee_id:large.employees[(index*10+offset)%large.employees.length].id,demand_id:demand.id,fixed:false,segments:[]})));
  }
  large.id+=':browser-performance';
  const input={name:'synthetic-large-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(large))};
  const importMs=await measure(()=>uploadProject(input));
  await navigate('team');
  const matrixEditMs=await measure(()=>page.locator('.matrix-cell').first().click());
  const searchMs=await measure(async()=>{
    await page.fill('#matrixSearch','Testperson 120');
    await page.waitForFunction(()=>document.querySelector('#matrix tbody').textContent.includes('Testperson 120'));
  });
  assert.equal(await page.locator('#matrix tbody tr').count(),1);
  await page.fill('#matrixSearch','');
  const planMs=await measure(()=>navigate('plan'));
  assert.equal(await page.locator('#calendar tbody tr').count(),30);
  const firstPage=await page.locator('#calendar tbody').innerText();
  const nextPageMs=await measure(()=>page.getByRole('button',{name:'Planzeilen: nächste Seite',exact:true}).click());
  assert.notEqual(await page.locator('#calendar tbody').innerText(),firstPage);
  assert.equal(await page.locator('#calendar tbody tr').count(),30);
  assert.equal(await page.locator('#plan tbody tr').count(),0,'Assignment editor is built only when opened');
  const detailsMs=await measure(()=>page.locator('#assignmentDetails summary').click());
  assert.equal(await page.locator('#plan tbody tr').count(),40);
  const domNodes=await page.locator('*').count();
  const selects=await page.locator('#plan select').count();
  assert.equal(selects,0,'Employee pickers are created on demand, not per assignment');
  assert(domNodes<15000,`Large project remains bounded in DOM (${domNodes} nodes)`);
  for(const [name,value]of Object.entries({importMs,matrixEditMs,searchMs,planMs,nextPageMs,detailsMs}))assert(value<10000,`${name} stays responsive: ${value}ms`);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await screenshot('large-mobile.png');
  await page.setViewportSize({width:1440,height:1000});
  await screenshot('large-plan.png');
  const metrics={fixture,chromium:page.context().browser().version(),platform:process.platform,architecture:process.arch,employees:large.employees.length,days:31,assignments:large.assignments.length,importMs,matrixEditMs,searchMs,planMs,nextPageMs,detailsMs,domNodes};
  fs.writeFileSync(path.join(state,'ui-performance.json'),JSON.stringify(metrics,null,2));
  if(process.env.WEB_TEST_SCREENSHOT_DIR)fs.writeFileSync(path.join(process.env.WEB_TEST_SCREENSHOT_DIR,'ui-performance.json'),JSON.stringify(metrics,null,2));
  console.log('Browser product flow and UI measurements: '+JSON.stringify(metrics));
};
